export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
    START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
    FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST',
    RECEIVED_NOTIFICATIONS: 'RECEIVED_NOTIFICATIONS'
}